# Generated by Django 5.2.6 on 2025-09-30 09:39

import django.db.models.deletion
import skillsbridge_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('poly', 'Polytechnic'), ('jc', 'Junior College'), ('uni', 'University')], default='poly', max_length=10)),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('employment_rate', 'Employment Rate'), ('median_salary', 'Median Salary'), ('demand_growth', 'Demand Growth')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('dataset_vintage', models.IntegerField()),
                ('source_name', models.CharField(max_length=128)),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.course')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.industry')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlanNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=16)),
                ('ref_id', models.CharField(max_length=36)),
                ('order_idx', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skillsbridge_core.savedplan')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=1.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.skill')),
            ],
            options={
                'unique_together': {('course', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(through='skillsbridge_core.CourseSkill', to='skillsbridge_core.skill'),
        ),
    ]
