# Generated by Django 5.2.6 on 2025-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
