# Generated by Django 5.2.6 on 2025-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0002_course_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='employment_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='median_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
