# Generated by Django 5.2.6 on 2025-10-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0003_course_employment_rate_course_median_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicative_grade', models.CharField(max_length=50)),
                ('grade_type', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.course')),
            ],
        ),
    ]
