# Generated by Django 5.2.6 on 2025-10-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0004_courseigp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseigp',
            options={'ordering': ['qualification']},
        ),
        migrations.AddField(
            model_name='courseigp',
            name='qualification',
            field=models.CharField(choices=[('alevel', 'A-Level'), ('poly', 'Polytechnic'), ('olevel', 'O-Level')], default='poly', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courseigp',
            unique_together={('course', 'qualification')},
        ),
    ]
