# Generated by Django 5.2.6 on 2025-10-26 17:10

import django.db.models.deletion
import skillsbridge_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0007_bookmark_delete_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaToDegree',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('degree', models.ForeignKey(limit_choices_to={'level': 'uni'}, on_delete=django.db.models.deletion.CASCADE, related_name='diploma_sources', to='skillsbridge_core.course')),
                ('diploma', models.ForeignKey(limit_choices_to={'level': 'poly'}, on_delete=django.db.models.deletion.CASCADE, related_name='degree_pathways', to='skillsbridge_core.course')),
            ],
            options={
                'unique_together': {('diploma', 'degree')},
            },
        ),
    ]
