# Generated by Django 5.2.6 on 2025-10-26 17:30

import django.db.models.deletion
import skillsbridge_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0008_diplomatodegree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.CharField(default=skillsbridge_core.models.uid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='skillsbridge_core.industry')),
                ('skills', models.ManyToManyField(blank=True, to='skillsbridge_core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='skillsbridge_core.career')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='skillsbridge_core.course')),
            ],
            options={
                'unique_together': {('course', 'career')},
            },
        ),
    ]
