# Generated by Django 5.2.6 on 2025-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0009_career_coursecareer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseigp',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
