# Generated by Django 5.2.6 on 2025-11-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0010_courseigp_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseigp',
            unique_together={('course', 'qualification', 'year')},
        ),
    ]
