# Generated by Django 5.2.6 on 2025-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0011_alter_courseigp_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseigp',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
