# Generated by Django 5.2.6 on 2025-11-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0012_courseigp_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseigp',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.course'),
        ),
    ]
