# Generated by Django 5.2.6 on 2025-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0013_alter_courseigp_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseigp',
            unique_together={('course', 'qualification', 'year', 'institution')},
        ),
    ]
