# Generated by Django 5.2.6 on 2025-11-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0014_alter_courseigp_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseigp',
            unique_together={('course', 'qualification', 'year', 'grade_type', 'institution')},
        ),
    ]
