# Generated by Django 5.2.6 on 2025-11-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0015_alter_courseigp_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_intake', models.IntegerField(blank=True, null=True)),
                ('intl_pct', models.FloatField(blank=True, null=True)),
                ('male_pct', models.FloatField(blank=True, null=True)),
                ('female_pct', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_records', to='skillsbridge_core.course')),
            ],
            options={
                'unique_together': {('course', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GESRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('employment_rate', models.FloatField()),
                ('median_salary', models.IntegerField()),
                ('top_jobs', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ges_records', to='skillsbridge_core.course')),
            ],
            options={
                'unique_together': {('course', 'year')},
            },
        ),
    ]
