# Generated by Django 5.2.6 on 2025-11-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0016_courseintake_gesrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseintake',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseintake',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillsbridge_core.course'),
        ),
    ]
