# Generated by Django 5.2.6 on 2025-11-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsbridge_core', '0017_alter_courseintake_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesrecord',
            name='top_jobs',
        ),
        migrations.AddField(
            model_name='gesrecord',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gesrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsbridge_core.course'),
        ),
        migrations.AlterField(
            model_name='gesrecord',
            name='employment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gesrecord',
            name='median_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
